projmoc2/gest_patr/urls.py
from django.conf.urls import url
from . import views

app_name = 'gest_partr'

urlpatterns = [
    url(r'^$',views.AboutView.as_view(),name='about'),

    url(r'^bem/lista/$',views.BemListView.as_view(),name='bens_lista'),
    url(r'^bem/(?P<pk>\d+)$', views.BemDetailView.as_view(), name='bem_detalhe'),
    url(r'^bem/new/$', views.CreateBemView.as_view(), name='bem_novo'),
    url(r'^bem/(?P<pk>\d+)/editar/$', views.BemUpdateView.as_view(), name='bem_alterar'),
    url(r'^bem/(?P<pk>\d+)/remover/$', views.BemDeleteView.as_view(), name='bem_remover'),
    url(r'^bem/api/lista/$',views.BemList.as_view(),name='bens-lista'),
    url(r'^bem/api/(?P<pk>\d+)$', views.BemDetail.as_view(), name='bem-detalhe'),

    url(r'^uge/lista/$',views.UgeListView.as_view(),name='uge_lista'),
    url(r'^uge/(?P<pk>\d+)$', views.UgeDetailView.as_view(), name='uge_detalhe'),
    url(r'^uge/new/$', views.CreateUgeView.as_view(), name='uge_novo'),
    url(r'^uge/(?P<pk>\d+)/editar/$', views.UgeUpdateView.as_view(), name='uge_alterar'),
    url(r'^uge/(?P<pk>\d+)/remover/$', views.UgeDeleteView.as_view(), name='uge_remover'),
    url(r'^uge/api/lista/$',views.UgeList.as_view(),name='uge-lista'),
    url(r'^uge/api/(?P<pk>\d+)$', views.UgeDetail.as_view(), name='uge-detalhe'),

    url(r'^ugb/lista/$',views.UgbListView.as_view(),name='ugb_lista'),
    url(r'^ugb/(?P<pk>\d+)$', views.UgbDetailView.as_view(), name='ugb_detalhe'),
    url(r'^ugb/new/$', views.CreateUgbView.as_view(), name='ugb_novo'),
    url(r'^ugb/(?P<pk>\d+)/editar/$', views.UgbUpdateView.as_view(), name='ugb_alterar'),
    url(r'^ugb/(?P<pk>\d+)/remover/$', views.UgbDeleteView.as_view(), name='ugb_remover'),
    url(r'^ugb/api/lista/$',views.UgbList.as_view(),name='ugb-lista'),
    url(r'^ugb/api/(?P<pk>\d+)$', views.UgbDetail.as_view(), name='ugb-detalhe'),

    url(r'^sector/lista/$',views.SectorListView.as_view(),name='sector_lista'),
    url(r'^sector/(?P<pk>\d+)$', views.SectorDetailView.as_view(), name='sector_detalhe'),
    url(r'^sector/new/$', views.CreateSectorView.as_view(), name='sector_novo'),
    url(r'^sector/(?P<pk>\d+)/editar/$', views.SectorUpdateView.as_view(), name='sector_alterar'),
    url(r'^sector/(?P<pk>\d+)/remover/$', views.SectorDeleteView.as_view(), name='sector_remover'),
    url(r'^sector/api/lista/$',views.SectorList.as_view(),name='sector-lista'),
    url(r'^sector/api/(?P<pk>\d+)$', views.SectorDetail.as_view(), name='sector-detalhe'),

    url(r'^subsector/lista/$',views.SubSectorListView.as_view(),name='subsector_lista'),
    url(r'^subsector/(?P<pk>\d+)$', views.SubSectorDetailView.as_view(), name='subsector_detalhe'),
    url(r'^subsector/new/$', views.CreateSubSectorView.as_view(), name='subsector_novo'),
    url(r'^subsector/(?P<pk>\d+)/editar/$', views.SubSectorUpdateView.as_view(), name='subsector_alterar'),
    url(r'^subsector/(?P<pk>\d+)/remover/$', views.SubSectorDeleteView.as_view(), name='subsector_remover'),
    url(r'^subsector/api/lista/$',views.SubSectorList.as_view(),name='subsector-lista'),
    url(r'^subsector/api/(?P<pk>\d+)$', views.SubSectorDetail.as_view(), name='subsector-detalhe'),

    url(r'^fornecedor/lista/$',views.FornecedorListView.as_view(),name='fornecedor_lista'),
    url(r'^fornecedor/(?P<pk>\d+)$', views.FornecedorDetailView.as_view(), name='fornecedor_detalhe'),
    url(r'^fornecedor/new/$', views.CreateFornecedorView.as_view(), name='fornecedor_novo'),
    url(r'^fornecedor/(?P<pk>\d+)/editar/$', views.FornecedorUpdateView.as_view(), name='fornecedor_alterar'),
    url(r'^fornecedor/(?P<pk>\d+)/remover/$', views.FornecedorDeleteView.as_view(), name='fornecedor_remover'),
    url(r'^fornecedor/api/lista/$',views.FornecedorList.as_view(),name='fornecedor-lista'),
    url(r'^fornecedor/api/(?P<pk>\d+)$', views.FornecedorDetail.as_view(), name='fornecedor-detalhe'),
]

projmoc2/projmoc2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('gest_patr.urls',namespace='gest_patr')),
    url(r'accounts/login/$', LoginView.as_view(), name='login'),
    url(r'accounts/logout/$', LogoutView.as_view(), name='logout',kwargs={'next_page':'/'}),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projmoc2/gest_patr/forms.py
from django import forms

from .models import Bem, Uge, Ugb, Sector, SubSector, Fornecedor

class UgeForm(forms.ModelForm):

    class Meta:
        model = Uge
        fields = ('cod','designacoes')

class UgbForm(forms.ModelForm):

    class Meta:
        model = Ugb
        fields = ('cod','designacoes')

class SubSectorForm(forms.ModelForm):

    class Meta:
        model = SubSector
        fields = ('cod','nome','sector')

class SectorForm(forms.ModelForm):

    class Meta:
        model = Sector
        # Entender como mudar o nome desses campos no formulário
        fields = ('cod',
                    'nome',
                    'ugb',
                    'provincia',
                    'distrito',
                    'postAdmin',
                    'localidade',
                    'classificadorTerr',
                    'bairro',
                    'endereco')

class FornecedorForm(forms.ModelForm):

    class Meta:
        model = Fornecedor
        fields = ('nome','nuit', 'enderecoFornecedor','cidade')

class BemForm(forms.ModelForm):

    class Meta:
        model = Bem
        fields = ('numOrdem',
                'nome',
                'uge',
                'ugb',
                'sector',
                'codClassificacaoGeral',
                'designacao',
                'marca',
                'numeroSerie',
                'NIP',
                'comprimento',
                'largura',
                'altura',
                'cor',
                'materialPredominante',
                'estadoBem',
                'tipoAquisicao',
                'dataAquisicao',
                'valor',
                'fornecedor',
                'tipoComprovativo',
                'nroComprovativo',
                'assistenciaTecnica',
                'garantia',
                'utilizador',
                'observacoes',
                'preenchidoPor',
                'responsavel')

# Caso queira mudar o CSS da classe de algum campo específico do formulário.
        # widgets = {
        #     'name': forms.TextInput(attrs={'class': 'textinputclass'}),
        #     'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'}),
        # }

projmoc2/gest_patr/views.py
from django.shortcuts import render, get_object_or_404, redirect
from rest_framework import generics


# from django.contrib.auth.decorators import login_required
from .models import Bem, Uge, Ugb, Sector, SubSector, Fornecedor
from django.utils import timezone
from .forms import BemForm, UgeForm, UgbForm, SectorForm, SubSectorForm, FornecedorForm
from .serializers import BemSerializer, UgeSerializer, UgbSerializer, SectorSerializer, SubsectorSerializer, FornecedorSerializer

from django.views.generic import (TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)

from django.urls import reverse_lazy
# from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
class AboutView(TemplateView):
    template_name = 'about.html'

class BemListView(ListView):
    model = Bem

    def get_queryset(self):
        return Bem.objects.filter(dataPreenchimento__lte=timezone.now()).order_by('-dataPreenchimento')

class BemDetailView(DetailView):
    model = Bem

class CreateBemView(CreateView):
    login_url = '/login/'
    redirect_field_name = 'bem_detalhe.html'

    form_class = BemForm
    model = Bem

class BemUpdateView(UpdateView):
    login_url = '/login/'
    redirect_field_name = 'bem_detalhe.html'

    form_class = BemForm

    model = Bem

class BemDeleteView(DeleteView):
    model = Bem
    success_url = reverse_lazy('gest_patr:bens_lista')

class BemList(generics.ListCreateAPIView):

    queryset = Bem.objects.all()
    serializer_class = BemSerializer

class BemDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Bem.objects.all()
    serializer_class = BemSerializer

##########################################################
##  Uge
##########################################################

class UgeListView(ListView):
    model = Uge

    def get_queryset(self):
        return Uge.objects.order_by('cod')

class UgeDetailView(DetailView):
    model = Uge

class CreateUgeView(CreateView):
    login_url = '/login/'
    redirect_field_name = 'uge_detalhe.html'

    form_class = UgeForm
    model = Uge

class UgeUpdateView(UpdateView):
    login_url = '/login/'
    redirect_field_name = 'uge_detalhe.html'

    form_class = UgeForm

    model = Uge

class UgeDeleteView(DeleteView):
    model = Uge
    success_url = reverse_lazy('gest_patr:uge_lista')

class UgeList(generics.ListCreateAPIView):

    queryset = Uge.objects.all()
    serializer_class = UgeSerializer

class UgeDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Uge.objects.all()
    serializer_class = UgeSerializer

##########################################################
##  Ugb
##########################################################

class UgbListView(ListView):
    model = Ugb

    def get_queryset(self):
        return Ugb.objects.order_by('cod')

class UgbDetailView(DetailView):
    model = Ugb

class CreateUgbView(CreateView):
    login_url = '/login/'
    redirect_field_name = 'ugb_detalhe.html'

    form_class = UgbForm
    model = Ugb

class UgbUpdateView(UpdateView):
    login_url = '/login/'
    redirect_field_name = 'ugb_detalhe.html'

    form_class = UgbForm

    model = Ugb

class UgbDeleteView(DeleteView):
    model = Ugb
    success_url = reverse_lazy('gest_patr:ugb_lista')

class UgbList(generics.ListCreateAPIView):

    queryset = Ugb.objects.all()
    serializer_class = UgbSerializer

class UgbDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Ugb.objects.all()
    serializer_class = UgbSerializer

##########################################################
##  Sector
##########################################################

class SectorListView(ListView):
    model = Sector

    def get_queryset(self):
        return Sector.objects.order_by('cod')

class SectorDetailView(DetailView):
    model = Sector

class CreateSectorView(CreateView):
    login_url = '/login/'
    redirect_field_name = 'sector_detalhe.html'

    form_class = SectorForm
    model = Sector

class SectorUpdateView(UpdateView):
    login_url = '/login/'
    redirect_field_name = 'sector_detalhe.html'

    form_class = SectorForm

    model = Sector

class SectorDeleteView(DeleteView):
    model = Sector
    success_url = reverse_lazy('gest_patr:sector_lista')

class SectorList(generics.ListCreateAPIView):

    queryset = Sector.objects.all()
    serializer_class = SectorSerializer

class SectorDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Sector.objects.all()
    serializer_class = SectorSerializer

##########################################################
##  SubSector
##########################################################

class SubSectorListView(ListView):
    model = SubSector

    def get_queryset(self):
        return SubSector.objects.order_by('cod')

class SubSectorDetailView(DetailView):
    model = SubSector

class CreateSubSectorView(CreateView):
    login_url = '/login/'
    redirect_field_name = 'subsector_detalhe.html'

    form_class = SubSectorForm
    model = SubSector

class SubSectorUpdateView(UpdateView):
    login_url = '/login/'
    redirect_field_name = 'subsector_detalhe.html'

    form_class = SubSectorForm

    model = SubSector

class SubSectorDeleteView(DeleteView):
    model = SubSector
    success_url = reverse_lazy('gest_patr:subsector_lista')

class SubSectorList(generics.ListCreateAPIView):

    queryset = SubSector.objects.all()
    serializer_class = SubsectorSerializer

class SubSectorDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = SubSector.objects.all()
    serializer_class = SubsectorSerializer

##########################################################
##  Fornecedor
##########################################################

class FornecedorListView(ListView):
    model = Fornecedor

    def get_queryset(self):
        return Fornecedor.objects.order_by('nuit')

class FornecedorDetailView(DetailView):
    model = Fornecedor

class CreateFornecedorView(CreateView):
    login_url = '/login/'
    redirect_field_name = 'fornecedor_detalhe.html'

    form_class = FornecedorForm
    model = Fornecedor

class FornecedorUpdateView(UpdateView):
    login_url = '/login/'
    redirect_field_name = 'fornecedor_detalhe.html'

    form_class = FornecedorForm

    model = Fornecedor

class FornecedorDeleteView(DeleteView):
    model = Fornecedor
    success_url = reverse_lazy('gest_patr:fornecedor_lista')

class FornecedorList(generics.ListCreateAPIView):

    queryset = Fornecedor.objects.all()
    serializer_class = FornecedorSerializer

class FornecedorDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Fornecedor.objects.all()
    serializer_class = FornecedorSerializer

projmoc2/gest_patr/templates/gest_patr/about.html
{% extends "blog/base.html" %}
{% block content %}
<h1>About me</h1>
<p>Thanks for visiting my blog! Check all this cool stuff about me!</p>

{% endblock %}

projmoc2/gest_patr/templates/gest_patr/bem_confirm_delete.html
{% extends "gest_patr/base.html" %}
{% block content %}
  <form action="" method="post">{% csrf_token %}
    <h4><p>Tem certeza que deseja remover "{{ object }}"?</p></h4>
    <hr><br><br>
    <a class="btn btn-primary" href="{% url 'gest_patr:bens_lista' %}">Voltar</a>
    <input class='btn btn-danger' type="submit" value="Confirmar" />
  </form>
{% endblock %}

projmoc2/gest_patr/templates/gest_patr/bem_form.html
{% extends 'gest_patr/base.html' %}

{% block content %}
    <h1>
      {% if not form.instance.pk %}
      Novo Bem
      {% else %}
      Atualizar Informações
      {% endif %}
      <button type="button" class="btn btn-success topright" onclick="location.href = '{% url 'gest_patr:bens_lista' %}';">Voltar</button>
    </h1>
    <hr>
    <br><br>
    <form method="POST" class="post-form">
    {% csrf_token %}
    <table class="table table-borderless table-hover table-sm">
      <!-- quebrar formulário -->
      {{form.as_table}}
    </table>
    <button type="submit" class="save btn btn-success">Salvar</button>
    </form>

{% endblock %}

projmoc2/gest_patr/templates/gest_patr/fornecedor_detail.html
 {% extends 'gest_patr/base.html' %}

{% block content %}


<h1 class='posttitle loader'>{{ fornecedor.nome }}
  <a class="btn btn-success topright" href="{% url 'gest_patr:fornecedor_lista' %}">Voltar</a>
</h1>
        <hr>
<br><br>
  <div class="container">
    <div class="centerstage">
      <div class="table-responsive">
        <table class="table table-hover table-borderless table-sm">
          <tbody>
            <tr>
              <td><h6>Nome</h6></td>
              <td>{{ fornecedor.nome }}</td>
            </tr>
            <tr>
              <td><h6>NUIT</h6></td>
              <td>{{ fornecedor.nuit }}</td>
            </tr>
            <tr>
              <td><h6>Endereco</h6></td>
              <td>{{ fornecedor.enderecoFornecedor }}</td>
            </tr>
            <tr>
              <td><h6>Cidade</h6></td>
              <td>{{ fornecedor.cidade }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  <br><hr><br>
<a class="btn btn-primary" href="{% url 'gest_patr:fornecedor_alterar' pk=fornecedor.pk %}">Alterar</a>
<a class="btn btn-danger" href="{% url 'gest_patr:fornecedor_remover' pk=fornecedor.pk %}">Remover</a>

</div>

{% endblock %}

projmoc2/gest_patr/templates/gest_patr/fornecedor_form.html
{% extends 'gest_patr/base.html' %}

{% block content %}
    <h1>
      {% if not form.instance.pk %}
      Novo Fornecedor
      {% else %}
      Atualizar Informações
      {% endif %}
      <button type="button" class="btn btn-success topright" onclick="location.href = '{% url 'gest_patr:fornecedor_lista' %}';">Voltar</button>
    </h1>
    <hr>
    <br><br>
    <form method="POST" class="post-form">
    {% csrf_token %}
    <table class="table table-borderless table-hover table-sm">
      {{form.as_table}}
    </table>
    <button type="submit" class="save btn btn-success">Salvar</button>
    </form>

{% endblock %}

projmoc2/gest_patr/templates/gest_patr/fornecedor_list.html
{% extends 'gest_patr/base.html' %}

{% block content %}
<h1>Lista de Fornecedores
<button type="button" class="btn btn-success topright" onclick="location.href = '{% url 'gest_patr:fornecedor_novo' %}';">Novo</button>
</h1>
<hr>
<br><br>
<div class="centerstage">
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>NUIT</th>
          <th>Fornecedor</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for fornecedor in fornecedor_list %}
        <tr>
          <td><a href="{% url 'gest_patr:fornecedor_detalhe' pk=fornecedor.pk %}">{{ fornecedor.nuit }}</a></td>
          <td>{{ fornecedor.nome }}</td>
          <td>
            <a class="btn btn-primary btn-sm" href="{% url 'gest_patr:fornecedor_alterar' pk=fornecedor.pk %}">Alterar</span></a>
            <a class="btn btn-danger btn-sm" href="{% url 'gest_patr:fornecedor_remover' pk=fornecedor.pk %}">Remover</span></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

projmoc2/gest_patr/templates/gest_patr/sector_confirm_delete.html
{% extends "gest_patr/base.html" %}
{% block content %}
  <form action="" method="post">{% csrf_token %}
    <h4><p>Tem certeza que deseja remover "{{ object }}"?</p></h4>
    <hr><br><br>
    <a class="btn btn-primary" href="{% url 'gest_patr:sector_lista' %}">Voltar</a>
    <input class='btn btn-danger' type="submit" value="Confirmar" />
  </form>
{% endblock %}

projmoc2/gest_patr/templates/gest_patr/sector_list.html
{% extends 'gest_patr/base.html' %}

{% block content %}
<h1>Lista de Sectores
<button type="button" class="btn btn-success topright" onclick="location.href = '{% url 'gest_patr:sector_novo' %}';">Novo</button>
</h1>
<hr>
<br><br>
<div class="centerstage">
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>Código</th>
          <th>Sector</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for sector in sector_list %}
        <tr>
          <td><a href="{% url 'gest_patr:sector_detalhe' pk=sector.pk %}">{{ sector.cod }}</td>
          <td>{{ sector.nome}}</td>
          <td>
            <a class="btn btn-primary btn-sm" href="{% url 'gest_patr:sector_alterar' pk=sector.pk %}">Alterar</span></a>
            <a class="btn btn-danger btn-sm" href="{% url 'gest_patr:sector_remover' pk=sector.pk %}">Remover</span></a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

projmoc2/gest_patr/templates/gest_patr/subsector_list.html
{% extends 'gest_patr/base.html' %}

{% block content %}
<h1>Lista de Subsectores
<button type="button" class="btn btn-success topright" onclick="location.href = '{% url 'gest_patr:subsector_novo' %}';">Nova</button>
</h1>
<hr>
<br><br>
<div class="centerstage">
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>Cód.</th>
          <th>Subsector</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      {% for subsector in subsector_list %}
        <tr>
          <td><a href="{% url 'gest_patr:subsector_detalhe' pk=subsector.pk %}">{{ subsector.cod }}</a></h1>
          <td>{{ subsector.nome }}</td>
          <td>
            <a class="btn btn-primary btn-sm" href="{% url 'gest_patr:subsector_alterar' pk=subsector.pk %}">Alterar</span></a>
            <a class="btn btn-danger btn-sm" href="{% url 'gest_patr:subsector_remover' pk=subsector.pk %}">Remover</span></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

projmoc2/gest_patr/templates/gest_patr/ugb_confirm_delete.html
{% extends "gest_patr/base.html" %}
{% block content %}
  <form action="" method="post">{% csrf_token %}
    <h4><p>Tem certeza que deseja remover "{{ object }}"?</p></h4>
    <hr><br><br>
    <a class="btn btn-primary" href="{% url 'gest_patr:ugb_lista' %}">Voltar</a>
    <input class='btn btn-danger' type="submit" value="Confirmar" />
  </form>
{% endblock %}

projmoc2/gest_patr/templates/gest_patr/ugb_list.html
{% extends 'gest_patr/base.html' %}

{% block content %}
<h1>Lista de UGBs
<button type="button" class="btn btn-success topright" onclick="location.href = '{% url 'gest_patr:ugb_novo' %}';">Nova</button>
</h1>
<hr>
<br><br>
<div class="centerstage">
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>Cód.</th>
          <th>designações</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      {% for ugb in ugb_list %}
        <tr>
          <td><a href="{% url 'gest_patr:ugb_detalhe' pk=ugb.pk %}">{{ ugb.cod }}</a></h1>
          <td>{{ ugb.designacoes }}</td>
          <td>
            <a class="btn btn-primary btn-sm" href="{% url 'gest_patr:ugb_alterar' pk=ugb.pk %}">Alterar</span></a>
            <a class="btn btn-danger btn-sm" href="{% url 'gest_patr:ugb_remover' pk=ugb.pk %}">Remover</span></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

projmoc2/gest_patr/templates/gest_patr/uge_confirm_delete.html
{% extends "gest_patr/base.html" %}
{% block content %}
  <form action="" method="post">{% csrf_token %}
    <h4><p>Tem certeza que deseja remover "{{ object }}"?</p></h4>
    <hr><br><br>
    <a class="btn btn-primary" href="{% url 'gest_patr:uge_lista' %}">Voltar</a>
    <input class='btn btn-danger' type="submit" value="Confirmar" />
  </form>
{% endblock %}

projmoc2/gest_patr/templates/gest_patr/uge_form.html
{% extends 'gest_patr/base.html' %}

{% block content %}
    <h1>
      {% if not form.instance.pk %}
      Nova Uge
      {% else %}
      Atualizar Informações
      {% endif %}
      <button type="button" class="btn btn-success topright" onclick="location.href = '{% url 'gest_patr:uge_lista' %}';">Voltar</button>
    </h1>
    <hr>
    <br><br>
    <form method="POST" class="post-form">
    {% csrf_token %}
    <table class="table table-borderless table-hover table-sm">
      {{form.as_table}}
    </table>
    <button type="submit" class="save btn btn-success">Salvar</button>
    </form>

{% endblock %}

projmoc2/gest_patr/templates/gest_patr/uge_list.html
{% extends 'gest_patr/base.html' %}

{% block content %}
<h1>Lista de UGEs
<button type="button" class="btn btn-success topright" onclick="location.href = '{% url 'gest_patr:uge_novo' %}';">Nova</button>
</h1>
<hr>
<br><br>
<div class="centerstage">
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>Cód.</th>
          <th>designações</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for uge in uge_list %}
        <tr>
          <td><a href="{% url 'gest_patr:uge_detalhe' pk=uge.pk %}">{{ uge.cod }}</td>
          <td>{{ uge.designacoes }}</td>
          <td>
            <a class="btn btn-primary btn-sm" href="{% url 'gest_patr:uge_alterar' pk=uge.pk %}">Alterar</span></a>
            <a class="btn btn-danger btn-sm" href="{% url 'gest_patr:uge_remover' pk=uge.pk %}">Remover</span></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}